config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:'homes#top'
  resources:lists
  resources:chaos, only:[:new,:create]
  resources:chaoers

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chao.rb
class Chao < ApplicationRecord
end

app/models/chaoer.rb
class Chaoer < ApplicationRecord
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chaos_controller.rb
class ChaosController < ApplicationController
  def new
    @chao = Chao.new
  end

  def create
    @chao = Chao.new(chao_params)
    @chao.save
    redirect_to new
  end

  private

  def chao_params
    params.require(:chao).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chao_helper.rb
module ChaoHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/chaos/new.html.erb
<h1>Chao#new</h1>
<%= form_with model:@chao do |f| %>
<%= f.label:チャオの名前 %>
<%= f.text_field:name %>
<%= f.submit'保存' %>
<% end %>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chao Room</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Edit Data</h1>

<%= form_with model:@list do |f| %>

<h4>Chao's Name</h4>
<%= f.text_field:name %>

<h4>Attribute and Type</h4>
<%= f.text_area:body %>

<%= f.submit 'Save' %>

<% end %>

app/views/lists/index.html.erb
<h1>Chao-Data List</h1>

<% @lists.each do |list| %>

<p>Name</p>
<span><%= link_to list.name, chao_path(list.id) %></span>

<p>Image</p>
 <% if list.image.attached? %>
 <%= image_tag list.image,size:"200*200" %>
 <% else %>
  <%= image_tag 'no_image',size:"200*200" %>
 <% end %>

<% end %>

app/views/lists/new.html.erb
<h1>New Chao??</h1>
<%= form_with model:@data, url:'/lists',method: :post do |f| %>

 <h4>Chao's name</h4>
 <%= f.text_field:name %>

 <h4>Attribute and Type</h4>
 <%= f.text_area:body %>
 
 <h4>画像</h4>
 <%= f.file_field :image,accept:"image/*" %>

 <%= f.submit 'OK!' %>
<% end %>

app/views/lists/show.html.erb
<h2>Chao's Name</h2>
<p><%= @list.name %></p>

<h2>Chao's Attribute & Type</h2>
<p><%= @list.body %></p>

<p>Image</p>
 <% if @list.image.attached? %>
 <%= image_tag list.image,size:"300*300" %>
 <% else %>
  <%= image_tag 'no_image',size:"300*300" %>
 <% end %>

<%= link_to "削除",destroy_chao_path(@list.id),method: :delete,"data-confirm" => "本当に消すチャオ？" %>